-- Safe catalog bootstrap only. No incidents, observations, credentials, or
-- synthetic evidence are seeded. Every endpoint and target remains disabled
-- until licensing review and a real adapter release exist.

insert into core.providers (
  public_id, contract_version, slug, name, organization_type, homepage_url, jurisdiction, is_public
)
values
  ('018f0000-0000-7000-8000-000000000001', '1.1.0', 'nasa', 'NASA', 'government', 'https://www.nasa.gov/', 'United States', true),
  ('018f0000-0000-7000-8000-000000000002', '1.1.0', 'noaa', 'NOAA', 'government', 'https://www.noaa.gov/', 'United States', true),
  ('018f0000-0000-7000-8000-000000000003', '1.1.0', 'gdacs', 'Global Disaster Alert and Coordination System', 'intergovernmental', 'https://www.gdacs.org/', 'Global', true),
  ('018f0000-0000-7000-8000-000000000004', '1.1.0', 'open-meteo', 'Open-Meteo', 'commercial', 'https://open-meteo.com/', 'Global', true),
  ('018f0000-0000-7000-8000-000000000005', '1.1.0', 'hellenic-fire-service', 'Hellenic Fire Service', 'government', 'https://www.fireservice.gr/', 'Greece', true),
  ('018f0000-0000-7000-8000-000000000006', '1.1.0', 'greece-civil-protection', 'Greek Civil Protection', 'government', 'https://civilprotection.gov.gr/', 'Greece', true),
  ('018f0000-0000-7000-8000-000000000007', '1.1.0', 'european-commission-jrc', 'European Commission Joint Research Centre', 'intergovernmental', 'https://joint-research-centre.ec.europa.eu/', 'European Union', true),
  ('018f0000-0000-7000-8000-000000000008', '1.1.0', 'eumetnet', 'EUMETNET', 'intergovernmental', 'https://www.eumetnet.eu/', 'Europe', true),
  ('018f0000-0000-7000-8000-000000000009', '1.1.0', 'junta-castilla-y-leon', 'Junta de Castilla y Leon', 'government', 'https://www.jcyl.es/', 'Castilla y Leon, Spain', true),
  ('018f0000-0000-7000-8000-000000000010', '1.1.0', 'junta-andalucia', 'Junta de Andalucia', 'government', 'https://www.juntadeandalucia.es/', 'Andalusia, Spain', true)
on conflict (slug) do nothing;

-- CMR is a distinct metadata source from FIRMS detections and GIBS imagery.
-- NASA/LANCE collection metadata is approved for reuse under the recorded
-- Earthdata guidance, but collection remains operationally disabled until an
-- exact adapter artifact and least-privileged worker are deployed.
insert into core.sources (
  public_id,
  contract_version,
  provider_id,
  slug,
  name,
  description,
  product_family,
  default_trust_class,
  default_evidence_class,
  operational_scope,
  homepage_url,
  terms_url,
  license_code,
  license_name,
  attribution_text,
  license_status,
  commercial_use_allowed,
  redistribution_allowed,
  cache_ttl,
  retention_limit,
  contains_personal_data,
  sensitivity,
  default_freshness,
  default_max_staleness,
  enabled,
  is_public,
  metadata
)
values (
  '018f0000-0000-7000-8000-000000000115',
  '1.1.0',
  (select id from core.providers where slug = 'nasa'),
  'nasa-cmr-firemask',
  'NASA CMR VIIRS FireMask Granule Catalog',
  'CMR metadata for LANCE VIIRS FireMask NRT granules. Catalog footprints describe pass coverage only; pixel anomaly state is not assessed. LANCE NRT data carry the NASA near-real-time disclaimer and must be cited without implying NASA endorsement.',
  'firemask_granule_catalog',
  'official_observation',
  'satellite_pass_metadata',
  'mixed',
  'https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html',
  'https://www.earthdata.nasa.gov/engage/open-data-services-software/data-use-policy',
  'us_government_work',
  'U.S. Government Work / NASA Earthdata Data Use and Citation Guidance',
  'NASA EOSDIS Common Metadata Repository (CMR) / LANCE; acknowledge NASA and the applicable VIIRS mission data source. Near-real-time data are provided without warranty and are not for navigation or life-safety decisions.',
  'approved',
  true,
  true,
  interval '15 minutes',
  interval '90 days',
  false,
  'public',
  interval '15 minutes',
  interval '3 hours',
  false,
  true,
  '{"anomalyAssessment":"not_assessed","catalogMetadataOnly":true}'::jsonb
)
on conflict (slug) do nothing;

insert into core.sources (
  public_id,
  contract_version,
  provider_id,
  slug,
  name,
  description,
  product_family,
  default_trust_class,
  default_evidence_class,
  operational_scope,
  homepage_url,
  terms_url,
  license_code,
  license_status,
  default_freshness,
  default_max_staleness,
  enabled,
  is_public
)
values
  (
    '018f0000-0000-7000-8000-000000000101',
    '1.1.0',
    (select id from core.providers where slug = 'nasa'),
    'nasa-firms',
    'NASA FIRMS Active Fire Data',
    'Satellite thermal detections; detections are observations, not confirmed wildfire incidents.',
    'active_fire',
    'official_observation',
    'thermal_detection',
    'mixed',
    'https://firms.modaps.eosdis.nasa.gov/',
    'https://firms.modaps.eosdis.nasa.gov/content/academy/data_api/firms_api_use.html',
    'provider_terms',
    'unreviewed',
    interval '15 minutes',
    interval '3 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000102',
    '1.1.0',
    (select id from core.providers where slug = 'nasa'),
    'nasa-eonet',
    'NASA EONET Open Events',
    'Global event discovery aggregator; not local incident-command truth.',
    'natural_events',
    'official_aggregate',
    'incident_summary',
    'global_discovery',
    'https://eonet.gsfc.nasa.gov/',
    null,
    'provider_terms',
    'unreviewed',
    interval '30 minutes',
    interval '6 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000103',
    '1.1.0',
    (select id from core.providers where slug = 'gdacs'),
    'gdacs-alerts',
    'GDACS Disaster Alerts',
    'Global disaster alert context; not a substitute for local authority updates.',
    'disaster_alerts',
    'official_aggregate',
    'incident_summary',
    'global_discovery',
    'https://www.gdacs.org/',
    'https://www.gdacs.org/About/terms.aspx',
    'provider_terms',
    'unreviewed',
    interval '30 minutes',
    interval '6 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000104',
    '1.1.0',
    (select id from core.providers where slug = 'open-meteo'),
    'open-meteo-weather',
    'Open-Meteo Weather',
    'Modeled weather context queried around incident AOIs.',
    'weather_model',
    'modeled',
    'weather_model',
    'context',
    'https://open-meteo.com/',
    'https://open-meteo.com/en/terms',
    'provider_terms',
    'unreviewed',
    interval '15 minutes',
    interval '2 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000105',
    '1.1.0',
    (select id from core.providers where slug = 'noaa'),
    'noaa-nws-alerts',
    'NOAA/NWS Active Alerts',
    'Official United States watches, warnings, and advisories.',
    'weather_alerts',
    'authoritative',
    'hazard_advisory',
    'mixed',
    'https://www.weather.gov/documentation/services-web-api',
    'https://www.weather.gov/disclaimer',
    'us_government_work',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000106',
    '1.1.0',
    (select id from core.providers where slug = 'noaa'),
    'noaa-metar',
    'NOAA AviationWeather METAR',
    'Airport weather observations used as incident context.',
    'weather_observations',
    'official_observation',
    'weather_observation',
    'incident_operations',
    'https://aviationweather.gov/data/api/',
    'https://www.weather.gov/disclaimer',
    'us_government_work',
    'unreviewed',
    interval '10 minutes',
    interval '1 hour',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000107',
    '1.1.0',
    (select id from core.providers where slug = 'nasa'),
    'nasa-gibs',
    'NASA Global Imagery Browse Services',
    'Georeferenced satellite imagery context; imagery interpretation is not incident confirmation.',
    'satellite_imagery',
    'official_observation',
    'satellite_imagery',
    'context',
    'https://www.earthdata.nasa.gov/eosdis/science-system-description/eosdis-components/gibs',
    'https://www.earthdata.nasa.gov/engage/open-data-services-and-software/data-and-information-policy',
    'provider_terms',
    'unreviewed',
    interval '15 minutes',
    interval '6 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000108',
    '1.1.0',
    (select id from core.providers where slug = 'hellenic-fire-service'),
    'hellenic-fire-service-updates',
    'Hellenic Fire Service Incident Updates',
    'Official incident communications within Hellenic Fire Service jurisdiction.',
    'incident_updates',
    'authoritative',
    'authority_incident_update',
    'incident_operations',
    'https://www.fireservice.gr/',
    null,
    'provider_terms',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000109',
    '1.1.0',
    (select id from core.providers where slug = 'greece-civil-protection'),
    'greece-civil-protection-alerts',
    'Greek Civil Protection Alerts',
    'Official civil-protection warnings and public safety communications for Greece.',
    'civil_protection_alerts',
    'authoritative',
    'hazard_advisory',
    'incident_operations',
    'https://civilprotection.gov.gr/',
    null,
    'provider_terms',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000110',
    '1.1.0',
    (select id from core.providers where slug = 'european-commission-jrc'),
    'effis',
    'European Forest Fire Information System',
    'European wildfire discovery, danger, and situation context from EFFIS.',
    'wildfire_information_system',
    'official_aggregate',
    'incident_summary',
    'mixed',
    'https://effis.jrc.ec.europa.eu/',
    null,
    'provider_terms',
    'unreviewed',
    interval '15 minutes',
    interval '3 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000111',
    '1.1.0',
    (select id from core.providers where slug = 'european-commission-jrc'),
    'gwis',
    'Global Wildfire Information System',
    'Global wildfire discovery and modeled context from GWIS.',
    'wildfire_information_system',
    'official_aggregate',
    'incident_summary',
    'global_discovery',
    'https://gwis.jrc.ec.europa.eu/',
    null,
    'provider_terms',
    'unreviewed',
    interval '30 minutes',
    interval '6 hours',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000112',
    '1.1.0',
    (select id from core.providers where slug = 'eumetnet'),
    'meteoalarm',
    'Meteoalarm',
    'Official European severe-weather warning aggregation from national meteorological services.',
    'weather_alerts',
    'official_aggregate',
    'hazard_advisory',
    'context',
    'https://www.meteoalarm.org/',
    null,
    'provider_terms',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000113',
    '1.1.0',
    (select id from core.providers where slug = 'junta-castilla-y-leon'),
    'inforcyl',
    'INFORCYL',
    'Official regional forest-fire information for Castilla y Leon.',
    'regional_fire_information',
    'authoritative',
    'authority_incident_update',
    'incident_operations',
    'https://servicios.jcyl.es/inforcyl/',
    null,
    'provider_terms',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  ),
  (
    '018f0000-0000-7000-8000-000000000114',
    '1.1.0',
    (select id from core.providers where slug = 'junta-andalucia'),
    'infoca',
    'INFOCA',
    'Official regional forest-fire information for Andalusia.',
    'regional_fire_information',
    'authoritative',
    'authority_incident_update',
    'incident_operations',
    'https://www.juntadeandalucia.es/organismos/ema/areas/incendios-forestales/infoca.html',
    null,
    'provider_terms',
    'unreviewed',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true
  )
on conflict (slug) do nothing;

insert into core.endpoints (
  public_id,
  contract_version,
  source_id,
  endpoint_key,
  name,
  endpoint_kind,
  source_kind,
  authority_scopes,
  content_policy,
  license_policy,
  transport,
  base_url,
  http_method,
  auth_mode,
  credential_ref,
  trust_class,
  evidence_class,
  authoritativeness_scope,
  coverage_scope,
  poll_interval,
  expected_source_latency,
  freshness,
  max_staleness,
  supports_bbox,
  supports_cursor,
  supports_backfill,
  request_template
)
values
  (
    '018f0000-0000-7000-8000-000000000201',
    '1.1.0',
    (select id from core.sources where slug = 'nasa-firms'),
    'area-csv',
    'FIRMS Area CSV API',
    'dataset',
    'sensor',
    array['thermal_anomaly'],
    'structured_data',
    'provider_terms',
    'http_poll',
    'https://firms.modaps.eosdis.nasa.gov/api/area/csv',
    'GET',
    'query_secret',
    'FIRMS_MAP_KEY',
    'official_observation',
    'thermal_detection',
    'Satellite thermal anomaly observation only; not incident confirmation or severity.',
    'global',
    interval '15 minutes',
    interval '3 hours',
    interval '15 minutes',
    interval '3 hours',
    true,
    false,
    true,
    '{"credential_parameter":"map_key","products":["VIIRS_SNPP_NRT","VIIRS_NOAA20_NRT","VIIRS_NOAA21_NRT","MODIS_NRT"]}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000202',
    '1.1.0',
    (select id from core.sources where slug = 'nasa-eonet'),
    'open-events',
    'EONET Open Events API',
    'feed',
    'official_context',
    array['local_context'],
    'structured_data',
    'provider_terms',
    'http_poll',
    'https://eonet.gsfc.nasa.gov/api/v3/events',
    'GET',
    'none',
    null,
    'official_aggregate',
    'incident_summary',
    'Discovery context only.',
    'global',
    interval '30 minutes',
    interval '6 hours',
    interval '30 minutes',
    interval '6 hours',
    false,
    false,
    false,
    '{"status":"open","category":"wildfires"}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000203',
    '1.1.0',
    (select id from core.sources where slug = 'gdacs-alerts'),
    'event-list',
    'GDACS Event List API',
    'feed',
    'official_context',
    array['local_context'],
    'structured_data',
    'provider_terms',
    'http_poll',
    'https://www.gdacs.org/gdacsapi/api/events/geteventlist/SEARCH',
    'GET',
    'none',
    null,
    'official_aggregate',
    'incident_summary',
    'Discovery and corroboration only.',
    'global',
    interval '30 minutes',
    interval '6 hours',
    interval '30 minutes',
    interval '6 hours',
    false,
    false,
    true,
    '{}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000204',
    '1.1.0',
    (select id from core.sources where slug = 'open-meteo-weather'),
    'forecast',
    'Open-Meteo Forecast API',
    'model',
    'model',
    array['weather_model'],
    'derived_model',
    'provider_terms',
    'http_poll',
    'https://api.open-meteo.com/v1/forecast',
    'GET',
    'none',
    null,
    'modeled',
    'weather_model',
    'Modeled context; not an on-site weather observation.',
    'global',
    interval '15 minutes',
    interval '15 minutes',
    interval '15 minutes',
    interval '2 hours',
    true,
    false,
    true,
    '{"timezone":"GMT"}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000205',
    '1.1.0',
    (select id from core.sources where slug = 'noaa-nws-alerts'),
    'active-alerts',
    'NWS Active Alerts API',
    'feed',
    'official_alert',
    array['protective_instruction', 'local_context'],
    'official_content',
    'provider_terms',
    'http_poll',
    'https://api.weather.gov/alerts/active',
    'GET',
    'none',
    null,
    'authoritative',
    'hazard_advisory',
    'Authoritative only within the issuing United States jurisdiction and validity window.',
    'national',
    interval '5 minutes',
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    true,
    true,
    false,
    '{"status":"actual"}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000206',
    '1.1.0',
    (select id from core.sources where slug = 'noaa-metar'),
    'metar-json',
    'AviationWeather METAR API',
    'station',
    'measurement',
    array['weather_measurement'],
    'structured_data',
    'provider_terms',
    'http_poll',
    'https://aviationweather.gov/api/data/metar',
    'GET',
    'none',
    null,
    'official_observation',
    'weather_observation',
    'Station observation at the reporting airport; spatial representativeness varies.',
    'point_network',
    interval '10 minutes',
    interval '15 minutes',
    interval '10 minutes',
    interval '1 hour',
    true,
    false,
    true,
    '{"format":"json","hours":2}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000207',
    '1.1.0',
    (select id from core.sources where slug = 'nasa-gibs'),
    'wmts-epsg4326',
    'GIBS EPSG:4326 WMTS',
    'imagery',
    'sensor',
    array['satellite_imagery'],
    'official_content',
    'provider_terms',
    'manifest',
    'https://gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi',
    'GET',
    'none',
    null,
    'official_observation',
    'satellite_imagery',
    'Imagery context only; interpretation requires a separately versioned analysis step.',
    'global',
    interval '15 minutes',
    interval '3 hours',
    interval '15 minutes',
    interval '6 hours',
    true,
    false,
    true,
    '{"service":"WMTS","request":"GetCapabilities"}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000208',
    '1.1.0',
    (select id from core.sources where slug = 'hellenic-fire-service-updates'),
    'official-publications',
    'Hellenic Fire Service Official Publications',
    'page',
    'official_status',
    array['protective_instruction', 'incident_status'],
    'official_content',
    'provider_terms',
    'manual',
    'https://www.fireservice.gr/',
    null,
    'none',
    null,
    'authoritative',
    'authority_incident_update',
    'Authoritative only for statements issued by the Hellenic Fire Service.',
    'national',
    null,
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000209',
    '1.1.0',
    (select id from core.sources where slug = 'greece-civil-protection-alerts'),
    'official-alerts',
    'Greek Civil Protection Official Alerts',
    'page',
    'official_alert',
    array['protective_instruction', 'local_context'],
    'official_content',
    'provider_terms',
    'manual',
    'https://civilprotection.gov.gr/',
    null,
    'none',
    null,
    'authoritative',
    'hazard_advisory',
    'Authoritative only for warnings issued by Greek Civil Protection.',
    'national',
    null,
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000210',
    '1.1.0',
    (select id from core.sources where slug = 'effis'),
    'public-portal',
    'EFFIS Public Portal',
    'dataset',
    'official_context',
    array['local_context'],
    'official_content',
    'provider_terms',
    'manual',
    'https://effis.jrc.ec.europa.eu/',
    null,
    'none',
    null,
    'official_aggregate',
    'incident_summary',
    'European discovery and situational context; local authorities remain primary.',
    'regional',
    null,
    interval '15 minutes',
    interval '15 minutes',
    interval '3 hours',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000211',
    '1.1.0',
    (select id from core.sources where slug = 'gwis'),
    'public-portal',
    'GWIS Public Portal',
    'dataset',
    'official_context',
    array['local_context'],
    'official_content',
    'provider_terms',
    'manual',
    'https://gwis.jrc.ec.europa.eu/',
    null,
    'none',
    null,
    'official_aggregate',
    'incident_summary',
    'Global discovery and modeled context; local authorities remain primary.',
    'global',
    null,
    interval '30 minutes',
    interval '30 minutes',
    interval '6 hours',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000212',
    '1.1.0',
    (select id from core.sources where slug = 'meteoalarm'),
    'public-feeds',
    'Meteoalarm Public Feeds',
    'feed',
    'official_alert',
    array['local_context'],
    'official_content',
    'provider_terms',
    'manifest',
    'https://feeds.meteoalarm.org/',
    'GET',
    'none',
    null,
    'official_aggregate',
    'hazard_advisory',
    'Aggregated national meteorological warnings; issuing service defines authority.',
    'regional',
    interval '5 minutes',
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    false,
    true,
    true,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000213',
    '1.1.0',
    (select id from core.sources where slug = 'inforcyl'),
    'public-portal',
    'INFORCYL Public Portal',
    'page',
    'official_status',
    array['protective_instruction', 'incident_status', 'road_status'],
    'official_content',
    'provider_terms',
    'manual',
    'https://servicios.jcyl.es/inforcyl/',
    null,
    'none',
    null,
    'authoritative',
    'authority_incident_update',
    'Authoritative within Castilla y Leon and the publication validity window.',
    'regional',
    null,
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  ),
  (
    '018f0000-0000-7000-8000-000000000214',
    '1.1.0',
    (select id from core.sources where slug = 'infoca'),
    'public-portal',
    'INFOCA Public Portal',
    'page',
    'official_status',
    array['protective_instruction', 'incident_status', 'road_status'],
    'official_content',
    'provider_terms',
    'manual',
    'https://www.juntadeandalucia.es/organismos/ema/areas/incendios-forestales/infoca.html',
    null,
    'none',
    null,
    'authoritative',
    'authority_incident_update',
    'Authoritative within Andalusia and the publication validity window.',
    'regional',
    null,
    interval '5 minutes',
    interval '5 minutes',
    interval '30 minutes',
    false,
    false,
    false,
    '{"adapter_review_required":true}'::jsonb
  )
on conflict (source_id, endpoint_key) do nothing;

insert into core.endpoints (
  public_id,
  contract_version,
  source_id,
  endpoint_key,
  name,
  endpoint_kind,
  source_kind,
  authority_scopes,
  content_policy,
  license_policy,
  transport,
  base_url,
  http_method,
  auth_mode,
  credential_ref,
  trust_class,
  evidence_class,
  authoritativeness_scope,
  coverage_scope,
  poll_interval,
  expected_source_latency,
  freshness,
  max_staleness,
  timeout_ms,
  supports_bbox,
  supports_cursor,
  supports_backfill,
  request_template,
  response_contract,
  capabilities
)
values (
  '018f0000-0000-7000-8000-000000000215',
  '1.1.0',
  (select id from core.sources where slug = 'nasa-cmr-firemask'),
  'granules-umm-g-1-6-7',
  'CMR UMM-G 1.6.7 Granule Search',
  'dataset',
  'sensor',
  array['satellite_imagery'],
  'structured_data',
  'nasa_esdis_data_use_and_citation',
  'http_poll',
  'https://cmr.earthdata.nasa.gov/search/granules.umm_json_v1_6_7',
  'GET',
  'none',
  null,
  'official_observation',
  'satellite_pass_metadata',
  'Official CMR catalog metadata for granule temporal and spatial coverage only; pixel anomaly state is not assessed.',
  'global',
  interval '5 minutes',
  interval '3 hours',
  interval '15 minutes',
  interval '3 hours',
  15000,
  true,
  true,
  true,
  '{
    "accept":"application/vnd.nasa.cmr.umm_results+json; version=1.6.7",
    "clientId":"plomari-wildfire-tracker",
    "pagination":"CMR-Search-After",
    "provider":"LANCEMODIS",
    "requestHeaderAllowlist":["accept","client-id","x-request-id","cmr-search-after"],
    "responseFormat":"umm_json",
    "responseHeaderAllowlist":["content-type","cmr-hits","cmr-took","cmr-request-id","x-request-id","cmr-search-after","cmr-time-out","cmr-timed-out","retry-after"],
    "sortKeys":["-start_date","granule_ur"],
    "ummGVersion":"1.6.7"
  }'::jsonb,
  '{
    "identity":{"conceptId":"meta.concept-id","revisionId":"meta.revision-id"},
    "itemsPath":"items",
    "partialResponseHeaders":["cmr-time-out","cmr-timed-out"],
    "requiredFootprint":true
  }'::jsonb,
  '{
    "anomalyAssessment":"not_assessed",
    "pagination":"search_after",
    "products":["VNP14IMG_NRT","VJ114IMG_NRT","VJ214IMG_NRT"],
    "scanModes":["bootstrap","incremental","reconciliation"]
  }'::jsonb
)
on conflict (source_id, endpoint_key) do nothing;

insert into ingest.endpoint_state (endpoint_id, enabled)
select e.id, false
from core.endpoints as e
join core.sources as s on s.id = e.source_id
where s.slug in (
  'nasa-firms',
  'nasa-eonet',
  'gdacs-alerts',
  'open-meteo-weather',
  'noaa-nws-alerts',
  'noaa-metar',
  'nasa-gibs',
  'hellenic-fire-service-updates',
  'greece-civil-protection-alerts',
  'effis',
  'gwis',
  'meteoalarm',
  'inforcyl',
  'infoca',
  'nasa-cmr-firemask'
)
on conflict (endpoint_id) do nothing;

insert into core.collection_targets (
  public_id,
  contract_version,
  source_id,
  endpoint_id,
  target_key,
  name,
  visibility,
  enabled
)
select
  seed.public_id::core.uuid_v7,
  '1.1.0',
  s.id,
  e.id,
  seed.target_key,
  seed.name,
  'public',
  false
from (
  values
    ('018f0000-0000-7000-8000-000000000401'::uuid, 'nasa-firms', 'area-csv', 'global-discovery', 'FIRMS global discovery'),
    ('018f0000-0000-7000-8000-000000000402'::uuid, 'nasa-eonet', 'open-events', 'global-discovery', 'EONET global discovery'),
    ('018f0000-0000-7000-8000-000000000403'::uuid, 'gdacs-alerts', 'event-list', 'global-discovery', 'GDACS global discovery'),
    ('018f0000-0000-7000-8000-000000000404'::uuid, 'open-meteo-weather', 'forecast', 'global-context', 'Open-Meteo global context'),
    ('018f0000-0000-7000-8000-000000000405'::uuid, 'noaa-nws-alerts', 'active-alerts', 'us-discovery', 'NWS United States discovery'),
    ('018f0000-0000-7000-8000-000000000406'::uuid, 'noaa-metar', 'metar-json', 'global-stations', 'METAR global station context'),
    ('018f0000-0000-7000-8000-000000000407'::uuid, 'nasa-gibs', 'wmts-epsg4326', 'global-imagery', 'GIBS global imagery context'),
    ('018f0000-0000-7000-8000-000000000408'::uuid, 'hellenic-fire-service-updates', 'official-publications', 'greece-operations', 'Hellenic Fire Service Greece operations'),
    ('018f0000-0000-7000-8000-000000000409'::uuid, 'greece-civil-protection-alerts', 'official-alerts', 'greece-advisories', 'Greek Civil Protection advisories'),
    ('018f0000-0000-7000-8000-000000000410'::uuid, 'effis', 'public-portal', 'europe-discovery', 'EFFIS Europe discovery'),
    ('018f0000-0000-7000-8000-000000000411'::uuid, 'gwis', 'public-portal', 'global-discovery', 'GWIS global discovery'),
    ('018f0000-0000-7000-8000-000000000412'::uuid, 'meteoalarm', 'public-feeds', 'europe-warnings', 'Meteoalarm Europe warnings'),
    ('018f0000-0000-7000-8000-000000000413'::uuid, 'inforcyl', 'public-portal', 'castilla-y-leon-operations', 'INFORCYL Castilla y Leon operations'),
    ('018f0000-0000-7000-8000-000000000414'::uuid, 'infoca', 'public-portal', 'andalusia-operations', 'INFOCA Andalusia operations'),
    ('018f0000-0000-7000-8000-000000000415'::uuid, 'nasa-cmr-firemask', 'granules-umm-g-1-6-7', 'global-firemask-granules', 'CMR global VIIRS FireMask granule catalog')
) as seed(public_id, source_slug, endpoint_key, target_key, name)
join core.sources as s on s.slug = seed.source_slug
join core.endpoints as e on e.source_id = s.id and e.endpoint_key = seed.endpoint_key
on conflict (endpoint_id, target_key) do nothing;

-- configuration_sha256 is reproducible, not a sentinel: SHA-256 over the
-- identity v2 canonical UTF-8 JSON object with code-unit-sorted keys:
-- {endpointId,targetKind,requestConfig,geometry,geometryPrecisionM,
--  expectedCadenceSeconds,staleAfterSeconds,enabled}. Endpoint IDs are the
-- public UUIDs above; requestConfig is {}, geometry/precision are null, and
-- enabled is false. Changing any field requires a new revision and hash.
insert into core.collection_target_revisions (
  public_id,
  contract_version,
  identity_version,
  collection_target_id,
  endpoint_id,
  version_no,
  target_kind,
  configuration_sha256,
  scope,
  geometry_precision_source,
  claim_kind,
  operational_role,
  cadence,
  stale_after,
  enabled,
  request_params,
  effective_at
)
select
  seed.public_id::core.uuid_v7,
  '1.1.0',
  '2.0.0',
  t.id,
  e.id,
  1,
  seed.target_kind,
  seed.configuration_sha256,
  seed.scope,
  'not_applicable',
  seed.claim_kind,
  seed.operational_role,
  seed.cadence,
  seed.stale_after,
  false,
  '{}'::jsonb,
  timestamptz '2026-07-30 00:00:00+00'
from (
  values
    ('018f0000-0000-7000-8000-000000000501'::uuid, 'nasa-firms', 'area-csv', 'global-discovery', 'dataset', '309a06db9800af00eedc364890a3e29348ae18973f72ac348d7b36bac5ab52f2', 'global', 'thermal_detection', 'discovery', interval '15 minutes', interval '3 hours'),
    ('018f0000-0000-7000-8000-000000000502'::uuid, 'nasa-eonet', 'open-events', 'global-discovery', 'feed', '0fc10eccc270e6fef1317e5e0c6ca469e6c36d60820dfffee3d42869ce98f06e', 'global', 'incident_summary', 'discovery', interval '30 minutes', interval '6 hours'),
    ('018f0000-0000-7000-8000-000000000503'::uuid, 'gdacs-alerts', 'event-list', 'global-discovery', 'feed', '61c68e3152187f548a90c9cb83b9e881ca171f3c7213b4da862cfe5f107a690f', 'global', 'incident_summary', 'discovery', interval '30 minutes', interval '6 hours'),
    ('018f0000-0000-7000-8000-000000000504'::uuid, 'open-meteo-weather', 'forecast', 'global-context', 'global', 'b884b5bcacaec16c2de1a10c1868a88179666aef6b045493225cb0e16cc47d03', 'global', 'weather_model', 'context', interval '15 minutes', interval '2 hours'),
    ('018f0000-0000-7000-8000-000000000505'::uuid, 'noaa-nws-alerts', 'active-alerts', 'us-discovery', 'feed', '83e5ae84186552e5451f8d715f96a0395af146cd90eb7ee5e2f3898144c9bb11', 'regional', 'hazard_advisory', 'discovery', interval '5 minutes', interval '30 minutes'),
    ('018f0000-0000-7000-8000-000000000506'::uuid, 'noaa-metar', 'metar-json', 'global-stations', 'dataset', '408fad5c97463b3b3d6e46b79908ea9db334c70ec5e764ed1c69b8dae7d6f790', 'point_network', 'weather_observation', 'context', interval '10 minutes', interval '1 hour'),
    ('018f0000-0000-7000-8000-000000000507'::uuid, 'nasa-gibs', 'wmts-epsg4326', 'global-imagery', 'dataset', '9d2813a7d66adacf26c7406fe4bc67a6dae742f4e4dc8752da0a460774c7f0be', 'global', 'satellite_imagery', 'context', interval '15 minutes', interval '6 hours'),
    ('018f0000-0000-7000-8000-000000000508'::uuid, 'hellenic-fire-service-updates', 'official-publications', 'greece-operations', 'feed', 'a2da518ea13f65d10b275899b19420be0f28ad647665a5ed788159c7cd4e931e', 'regional', 'authority_incident_update', 'operations', interval '5 minutes', interval '30 minutes'),
    ('018f0000-0000-7000-8000-000000000509'::uuid, 'greece-civil-protection-alerts', 'official-alerts', 'greece-advisories', 'feed', '775ab1d0a523dccfc929ba601405562def1721f0183385f072b26be49534287b', 'regional', 'hazard_advisory', 'operations', interval '5 minutes', interval '30 minutes'),
    ('018f0000-0000-7000-8000-000000000510'::uuid, 'effis', 'public-portal', 'europe-discovery', 'dataset', '32b08252c7cbd30afc1f2382264892b388097400b93f54714e4aabfc758ca480', 'regional', 'incident_summary', 'discovery', interval '15 minutes', interval '3 hours'),
    ('018f0000-0000-7000-8000-000000000511'::uuid, 'gwis', 'public-portal', 'global-discovery', 'dataset', 'f6d0956d1cdc7db67f0dcda25232e19a46f9f3f4257861bf0864be9c58883e0d', 'global', 'incident_summary', 'discovery', interval '30 minutes', interval '6 hours'),
    ('018f0000-0000-7000-8000-000000000512'::uuid, 'meteoalarm', 'public-feeds', 'europe-warnings', 'feed', '837dab7aa8d662cc907721994af07940b91e7e8f19ec81fb3126f5c8a2476d8c', 'regional', 'hazard_advisory', 'context', interval '5 minutes', interval '30 minutes'),
    ('018f0000-0000-7000-8000-000000000513'::uuid, 'inforcyl', 'public-portal', 'castilla-y-leon-operations', 'feed', '2c56f5821e186a2cc0488910d28028641961d4f714f48b97dd34bd3d74f88a0e', 'regional', 'authority_incident_update', 'operations', interval '5 minutes', interval '30 minutes'),
    ('018f0000-0000-7000-8000-000000000514'::uuid, 'infoca', 'public-portal', 'andalusia-operations', 'feed', 'a2eed8a5c8834e7a506f52b1bde30812be937423ee8eed0bf1c9640412315863', 'regional', 'authority_incident_update', 'operations', interval '5 minutes', interval '30 minutes')
) as seed(public_id, source_slug, endpoint_key, target_key, target_kind, configuration_sha256, scope, claim_kind, operational_role, cadence, stale_after)
join core.sources as s on s.slug = seed.source_slug
join core.endpoints as e on e.source_id = s.id and e.endpoint_key = seed.endpoint_key
join core.collection_targets as t on t.endpoint_id = e.id and t.target_key = seed.target_key
on conflict (collection_target_id, version_no) do nothing;

-- The CMR target uses a five-minute incremental cadence, a 36-hour bootstrap,
-- and a periodic full reconciliation. It remains disabled. The hash is the
-- identity-v2 digest of this exact request configuration, the public endpoint
-- UUID, null geometry/precision, cadence=300, staleAfter=10800, enabled=false.
insert into core.collection_target_revisions (
  public_id,
  contract_version,
  identity_version,
  collection_target_id,
  endpoint_id,
  version_no,
  target_kind,
  configuration_sha256,
  scope,
  geometry_precision_source,
  claim_kind,
  operational_role,
  cadence,
  stale_after,
  enabled,
  request_params,
  effective_at
)
select
  '018f0000-0000-7000-8000-000000000515'::core.uuid_v7,
  '1.1.0',
  '2.0.0',
  target.id,
  endpoint.id,
  1,
  'global',
  '1d8dd3f510d333495f3c92ab245f6f1883a6cccb2e5323c0c2c17f832cd4f199',
  'global',
  'not_applicable',
  'satellite_pass_metadata',
  'context',
  interval '5 minutes',
  interval '3 hours',
  false,
  '{
    "bootstrapLookbackHours":36,
    "incrementalOverlapMinutes":10,
    "maximumPagesPerProduct":20,
    "pageSize":200,
    "products":[
      {"satellite":"Suomi-NPP","shortName":"VNP14IMG_NRT","version":"2"},
      {"satellite":"NOAA-20","shortName":"VJ114IMG_NRT","version":"2"},
      {"satellite":"NOAA-21","shortName":"VJ214IMG_NRT","version":"2"}
    ],
    "provider":"LANCEMODIS",
    "reconciliationIntervalHours":24,
    "responseFormat":"umm_json",
    "sortKeys":["-start_date","granule_ur"]
  }'::jsonb,
  timestamptz '2026-07-30 00:00:00+00'
from core.collection_targets as target
join core.endpoints as endpoint on endpoint.id = target.endpoint_id
join core.sources as source on source.id = target.source_id
where source.slug = 'nasa-cmr-firemask'
  and endpoint.endpoint_key = 'granules-umm-g-1-6-7'
  and target.target_key = 'global-firemask-granules'
on conflict (collection_target_id, version_no) do nothing;

insert into ingest.collection_target_state (
  collection_target_revision_id,
  collection_target_id
)
select revision.id, revision.collection_target_id
from core.collection_target_revisions as revision
where revision.public_id = '018f0000-0000-7000-8000-000000000515'
on conflict (collection_target_revision_id) do nothing;

-- No core.adapter_releases row is seeded for CMR. A release requires the
-- SHA-256 of the exact deployed collector artifact and its real commit; a
-- placeholder would make an undeployed adapter appear claimable.
